kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: easyshop-hpa
  namespace: easyshop
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: easyshop-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
